analogdevicesinc/libm2k

examples/analog/CMakeLists.txt
examples/analog/getSamples.cpp
include/libm2k/analog/genericanalogin.hpp
include/libm2k/analog/genericanalogout.hpp
include/libm2k/analog/m2kanalogin.hpp
include/libm2k/analog/m2kanalogout.hpp
include/libm2k/digital/m2kdigital.hpp
include/libm2k/utils/buffer.hpp
include/libm2k/utils/channel.hpp
include/libm2k/utils/devicein.hpp
include/libm2k/utils/deviceout.hpp
src/analog/genericanalogin.cpp
src/analog/genericanalogout.cpp
src/analog/m2kanalogin.cpp
src/analog/m2kanalogout.cpp
src/analog/private/genericanalogin_impl.cpp
src/analog/private/genericanalogout_impl.cpp
src/analog/private/m2kanalogin_impl.cpp
src/analog/private/m2kanalogout_impl.cpp
src/digital/m2kdigital.cpp
src/digital/private/m2kdigital_impl.cpp
src/private/m2kcalibration_impl.cpp
src/utils/buffer.cpp
src/utils/channel.cpp
src/utils/devicein.cpp
src/utils/deviceout.cpp
src/utils/private/buffer_impl.cpp
src/utils/private/channel_impl.cpp
src/utils/private/devicein_impl.cpp
src/utils/private/deviceout_impl.cpp

-Add methods for push and getSamples which accept raw pointers. 
This is useful in scenarios where std libraries are not available.
-Add methods which send and get interleaved data. 

Digital and Analog In / Out: Return and push interleaved samples and drop std::vector

---

CMakeLists.txt

Make sure the Configure/Generate step of CMake fails if SWIG is not found for Python or C# bindings.
The previous version disabled Python/C# if SWIG was not found. With this
changes, we make sure that if some bindings were required, those will be
built, not just ignored if SWIG is not found.

CMakeLists.txt: Fix SWIG detection

---

src/analog/private/m2kanalogout_impl.cpp
src/analog/private/m2khardwaretrigger_impl.cpp
src/digital/private/m2kdigital_impl.cpp

This PR introduces 3 fixes throughout the library:
- For the M2K Analog Out : The raw samples should not be altered at all before being pushed to the device. They should be pushed in the same state they were provided (only applies to raw values & pushRaw() methods) ( Related to issue #24 )
- M2K Digital : Delete the trigger object.
- M2K Hardware Trigger: Change the return type for the analog trigger level from int to double.

General: Add multiple fixes.

---

include/libm2k/contextbuilder.hpp
src/contextbuilder.cpp

In order to avoid multiple definition error, move ContextBuilder API implementation to source file.

ContextBuilder: define API functions as inline in order to avoid multiple definition error.

---

include/libm2k/analog/m2kanalogin.hpp
include/libm2k/analog/m2kanalogout.hpp
src/analog/m2kanalogin.cpp
src/analog/m2kanalogout.cpp
src/analog/private/m2kanalogout_impl.cpp

Expose methods to get the available sample rates for the M2k ADC and the M2k DAC.

M2kAnalogIn & M2kAnalogOut: get available samplerates

---

src/private/m2kcalibration_impl.cpp

PR #25 removed the raw value processing from the AnalogOut methods.
One of those methods was used in the calibration procedure. Only for this procedure, the specific processing is needed in order to have the board functional.

M2kCalibration: Fix the calibration procedure, which was broken in PR #25

---

include/libm2k/contextbuilder.hpp
include/libm2k/m2k.hpp

Doxygen Documentation: Update the Doxygen documentation to use Contexts instead of devices.
Forgot to add this in PR #41.

Update the Doxygen documentation to use Contexts

---

src/analog/private/m2kanalogout_impl.cpp

This fixes a mistake added in one of the previous commits. The cyclic mode attribute was no longer taken into consideration because of the wrong getter.

M2kAnalogOut: Fix cyclic mode for M2kAnalogOut.

---

include/libm2k/analog/genericanalogin.hpp
include/libm2k/analog/m2kanalogin.hpp
include/libm2k/analog/m2kanalogout.hpp
include/libm2k/digital/m2kdigital.hpp
include/libm2k/utils/buffer.hpp
include/libm2k/utils/devicein.hpp
src/analog/genericanalogin.cpp
src/analog/m2kanalogin.cpp
src/analog/private/genericanalogin_impl.cpp
src/analog/private/m2kanalogin_impl.cpp
src/analog/private/m2kanalogout_impl.cpp
src/digital/m2kdigital.cpp
src/digital/private/m2kdigital_impl.cpp
src/utils/buffer.cpp
src/utils/devicein.cpp
src/utils/private/buffer_impl.cpp
src/utils/private/devicein_impl.cpp
tools/m2kcli/commands/analog/analog_in.cpp
tools/m2kcli/commands/analog/analog_out.cpp

This PR updates some APIs to allow MATLAB binding creation. MATLAB requires const output pointers for output data arrays, and any provided (pushed) data must supply the number of samples in the array explicitly.
- [MATLAB Requirements](https://www.mathworks.com/help/matlab/matlab_external/define-matlab-interface-for-c-library.html) as documented by MathWorks
- The MATLAB binding are [built externally](https://github.com/analogdevicesinc/libm2k-matlab) based off these changes.

MATLAB requirements

---

examples/digital/main.cpp
include/libm2k/digital/m2kdigital.hpp
src/analog/private/m2kanalogin_impl.cpp
src/digital/m2kdigital.cpp
src/digital/private/m2kdigital_impl.cpp
src/utils/private/buffer_impl.cpp
tools/m2kcli/commands/digital/digital.cpp

1. Kernel buffers count can also be modified for the digital device. 
2. Allow the user to stop the digital output.
3. Allow the user to flush the input buffers. This drops all the old data from the buffers. Similar to the method provided for the analog devices.

M2kDigital: Manage kernel buffers count and flush buffers

---

src/analog/private/m2kpowersupply_impl.cpp
src/private/m2k_impl.cpp

If the previous libm2k context is closed without deinit, the M2kPowerSupply should continue to be functional (should not be reset to 0).
The M2K context will power down the DACs when it is closed.

M2kPowerSupply: Fix the behaviour of M2kPowerSupply at startup.

---

src/analog/private/m2kanalogin_impl.cpp
src/utils/private/buffer_impl.cpp

The "m2k-adc" requires all the channels to be enabled before acquiring data. All the channels must be enabled before a "iio_buffer_refill" call and then disabled if necessary
This should not be in the Buffer implementation, since other boards might not have the same behaviour.
Related to issues #58 and #59 .

M2kAnalogIn: Enable all the channels before refilling a buffer.

---

include/libm2k/analog/powersupply.hpp
include/libm2k/utils/channel.hpp
include/libm2k/utils/devicegeneric.hpp
include/libm2k/utils/devicein.hpp
include/libm2k/utils/deviceout.hpp
include/libm2k/utils/utils.hpp
src/analog/genericanalogout.cpp
src/analog/m2kanalogin.cpp
src/analog/powersupply.cpp
src/analog/private/dmm_impl.cpp
src/analog/private/genericanalogin_impl.cpp
src/analog/private/genericanalogout_impl.cpp
src/analog/private/m2kanalogin_impl.cpp
src/analog/private/m2kanalogout_impl.cpp
src/digital/private/genericdigital_impl.cpp
src/digital/private/m2kdigital_impl.cpp
src/private/m2k_impl.cpp
src/private/m2khardwaretrigger_impl.cpp
src/utils/channel.cpp
src/utils/devicegeneric.cpp
src/utils/devicein.cpp
src/utils/deviceout.cpp
src/utils/private/channel_impl.cpp
src/utils/private/devicegeneric_impl.cpp
src/utils/private/devicein_impl.cpp
src/utils/private/deviceout_impl.cpp
src/utils/utils.cpp

Previously, DeviceGeneric(the class which handles the iio_device interaction) scanned channels using their index (for DMMs) and using their name/ID for all the other devices (ADCs, DACs). It assumed that all the ADC or DAC channels are called "voltageX" which is not right.
In order to correctly use the channels, it scans them all based on the index. But this is not enough, the list of channels is separated in input and output channels and sorted based on the ID of each channel (could be improved) because the order in iio_device might change.
Related to issue #53 . 

Device Generic, In, Out: Add changes to the channel scanning system.

---

src/digital/private/m2kdigital_impl.cpp

After recent changes to the Device In/Out/Generic channels
scanning system, the enableChannel() method no longer works without
specifying the TX device for channel number checking. That is because
the GenericDevice(m2k-logic-analyzer) only has input channels.

M2kDigital: Fix TX enableChannel method

---

doc/CMakeLists.txt
include/libm2k/enums.hpp

Important enums, like trigger conditions, trigger mode or trigger source are in this generic enums.hpp file and they all need to be exposed in the Doxygen docs.

Doxygen: Add missing generic enums.hpp file to the documentation

---

include/libm2k/utils/buffer.hpp
include/libm2k/utils/channel.hpp
include/libm2k/utils/devicein.hpp
src/utils/buffer.cpp
src/utils/channel.cpp
src/utils/devicein.cpp
src/utils/private/buffer_impl.cpp
src/utils/private/channel_impl.cpp
src/utils/private/devicein_impl.cpp

Allow libm2k to handle data acquisition on devices with data sizes different from data size on "m2k-adc" in ADALM2000.

Device In: Handle all types of data sizes.

---

bindings/csharp/examples/analog.cs
bindings/python/examples/analog.py
examples/analog/main.cpp

Update all the examples to use the latest M2K trigger notations (added in PR #54  )

Examples: fix trigger notation usage

---

bindings/libm2k.i

libm2k.i: Generate Python documentation based on the documented classes and methods in C++.
When using libm2k in Python it is useful to be able to check what parameters are needed and also their type.
We can call **help** on any libm2k element in a python3 console and check the parameters. 
A simple example: 
**help(libm2k.M2kHardwareTrigger.setAnalogCondition)**
```
Help on function setAnalogCondition in module libm2k:
setAnalogCondition(self, chnIdx, cond)
setAnalogCondition(M2kHardwareTrigger self, unsigned int chnIdx, libm2k::M2K_TRIGGER_CONDITION_ANALOG cond)
Parameters
----------
chnIdx: unsigned int
cond: enum libm2k::M2K_TRIGGER_CONDITION_ANALOG
```

libm2k.i: Generate Python documentation 

---

bindings/libm2k.i
bindings/python/examples/analog_raw_bytes.py
examples/analog/sync_stream_diff_frequencies.cpp
include/libm2k/analog/genericanalogin.hpp
include/libm2k/analog/m2kanalogin.hpp
include/libm2k/analog/m2kanalogout.hpp
include/libm2k/digital/m2kdigital.hpp
include/libm2k/enums.hpp
include/libm2k/utils/buffer.hpp
include/libm2k/utils/channel.hpp
include/libm2k/utils/devicein.hpp
include/libm2k/utils/deviceout.hpp
src/analog/genericanalogin.cpp
src/analog/m2kanalogin.cpp
src/analog/m2kanalogout.cpp
src/analog/private/m2kanalogin_impl.cpp
src/analog/private/m2kanalogout_impl.cpp
src/digital/m2kdigital.cpp
src/digital/private/m2kdigital_impl.cpp
src/private/m2kcalibration_impl.cpp
src/utils/buffer.cpp
src/utils/channel.cpp
src/utils/devicein.cpp
src/utils/deviceout.cpp
src/utils/private/buffer_impl.cpp
src/utils/private/channel_impl.cpp
src/utils/private/devicein_impl.cpp
src/utils/private/deviceout_impl.cpp

Rework Python exposed methods for both Analog and Digital. Previously, users were not able to access in Python elements of objects like double*/short* because SWIG can't expose them by default.
In order to fix this, we added some typemaps and made use of memory view and buffer protocol in Python. 
In this PR we also expose conversion methods (for Analog In and Analog Out, from/to volts to/from raw).

Rework Python exposed methods.

---

src/analog/private/m2kpowersupply_impl.cpp

When the channel scanning mechanism changed, an extra channel appeared
(temp) for the power supply reading device. This change reordered the list
of channels and the "raw" value was read from the wrong channel.
This commit allows the powersupply to search the 2 channels based on
their name.

M2kPowerSupply: Fix channel reading.

---

src/private/m2kcalibration_impl.cpp

This mistake was visible only on some boards, where the difference
between the 2 ADC channel offsets was bigger and it influenced the
captured values.

M2kCalibration: Fix index in the ADC offset calibration.

---

src/private/m2khardwaretrigger_impl.cpp

MSVC displays warnings as errors in this case, where the methods only throw an exception instead of returning.
These methods in particular only throw an exception to the user, letting
him know that the operation is not possible. When building with CMake-GUI
and Microsoft Visual Studio on Windows, the compiler complains about the
missing return value. To ensure that these throw we call "throw" directly,
without using our own "throw" wrapper.

M2kHardwareTriggerImpl: Fix MSVC undefined behaviour.

---

include/libm2k/digital/m2kdigital.hpp
src/digital/m2kdigital.cpp
src/digital/private/m2kdigital_impl.cpp

Setting multiple kernel buffer on the output of the M2k Digital is possible in libiio so we also need to provide this possibility.

M2kDigital: Set kernel buffers count for the output of the M2k Digital.

---

src/analog/private/m2kanalogin_impl.cpp
src/private/m2k_impl.cpp

The vertical offset register in the device has dual purpose:
1. use as ADC offset for calibration
2. use as ADC vertical offset for measurement
This can cause some confusion when initializing the board
because it is not clear whether the value in the register is
the calibration value or the calibration+vertical offset value
This workaround will always set the vertical offset to 0 on deinitialization
and upon initialization the offset will be loaded from the register
(when no calibration is done)
The correct fix would be adding a separate caliboffset register in the firmware
which will clear up the confusion

M2kAnalogIn: correctly set/reset calib offset & vertical offset

---

appveyor.yml

The libm2k installer detects the Python version(32 or 64 bit) and
installs the appropriate artifacts. In order to use Python 32-bit
bindings on a 64-bit machine, these wheels cand be installed using pip.

appveyor.yml: Build Python wheels and deploy them as Appveyor artifacts.

---

CI/travis/before_install_darwin

Drop the upgrade step for brew packages.
Upgrading to the latest version of some packages can result in undefined behaviour so it's better if we install the package if it does not exist.

Travis CI:  Fix Python installation on OSX

---

CI/travis/before_install_linux

Travis fails on the Doxygen job because of a broken link.
Update the link to one that is working.

CI/travis/before_install_linux: Update Doxygen link on Travis-CI.

---

.travis.yml
53-adi-m2k-usb.rules
CI/travis/before_deploy
CI/travis/before_install_linux
CI/travis/make_linux
CMakeLists.txt
bindings/python/setup.py.cmakein
src/CMakeLists.txt

- This PR fixes some issues related to the OSX build (we don't want to build a framework by default). 
Some small changes were needed in order to create the .pkg and .tar.gz correctly.
- On Linux, we are building a .deb (for the base library) and a python .deb (only with python bindings) for every distribution on Travis-CI.
- Add code to deploy packages on the github release page for every newly created tag.
(2 .deb files and .tar.gz for Linux, and 2 .pkgs and 2 .tar.gz for OSX).

Travis: Deploy packages to Github release page

---

src/utils/private/buffer_impl.cpp

private/buffer_impl.cpp: Drop unnecessary initialization. 

private/buffer_impl.cpp: Drop unnecessary initialization.

---

src/m2khardwaretrigger.cpp

The comparison result should be < 0 if fw_version is < 0.24, and >0 when fw_version is > 0.24.
This allows the creation of the appropriate M2kHardwareTrigger object for the current firmware.

M2kHardwareTrigger.cpp: Fix comparison result for firmware versions.

---

include/libm2k/analog/m2kanalogin.hpp
include/libm2k/analog/m2kanalogout.hpp
include/libm2k/utils/buffer.hpp
include/libm2k/utils/devicein.hpp
include/libm2k/utils/deviceout.hpp
src/analog/m2kanalogin.cpp
src/analog/m2kanalogout.cpp
src/analog/private/m2kanalogin_impl.cpp
src/analog/private/m2kanalogout_impl.cpp
src/utils/buffer.cpp
src/utils/devicein.cpp
src/utils/deviceout.cpp
src/utils/private/buffer_impl.cpp
src/utils/private/devicein_impl.cpp
src/utils/private/deviceout_impl.cpp

This method cancels all pending buffer operations, such as getSamples(...) or push(...).

M2kAnalogIn/M2kAnalogOut: cancel all buffer operations.

---

include/libm2k/m2khardwaretrigger.hpp

When using this method together with setDigitalCondition, make sure setDigitalCondition happens first before calling setDigitalStreamingFlag(true)
Signed-off-by: Daniel Guramulta <daniel.guramulta@analog.com>

include/libm2k/m2khardwaretrigger.hpp: add a note on streaming flag

---

include/libm2k/digital/m2kdigital.hpp
src/digital/m2kdigital.cpp
src/digital/private/m2kdigital_impl.cpp

Those methods cancel all pending rx/tx buffer operations, such as getSamples(...) or push(...).

M2kDigital: Cancel all rx/tx buffer operations.

---

src/private/m2khardwaretrigger_impl.cpp

If the streaming was previously enabled, the trigger condition will no longer be active if we don't reset the flag.
From the docs: "If the streaming bit is set, after the trigger condition
is met data will be continuosly captured by the DMA.
The streaming bit must be set to 0 to reset triggering."

M2kHardwareTrigger: Set the streaming flag to 0 before enabling it.

---

include/libm2k/analog/m2kanalogin.hpp
include/libm2k/digital/m2kdigital.hpp
include/libm2k/utils/buffer.hpp
include/libm2k/utils/devicein.hpp
src/analog/m2kanalogin.cpp
src/analog/private/m2kanalogin_impl.cpp
src/digital/m2kdigital.cpp
src/digital/private/m2kdigital_impl.cpp
src/utils/buffer.cpp
src/utils/devicein.cpp
src/utils/private/buffer_impl.cpp
src/utils/private/devicein_impl.cpp

See issue #119 .
Provide getSamplesInVector methods. These methods will get the samples in a buffer that is created/owned by the client, therefore no allocation is done in the library. 

M2k Digital and Analog In capture: Get samples in vector 

---

src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogin_impl.hpp
src/m2kcalibration_impl.cpp
src/m2kcalibration_impl.hpp

Add the m2k-adc device as a member of M2kAnalogIn.
Save/load the calibration data from registers: offset, gain.
Save/load the vertical offset.

Calibration: Add handling for calibration data persistence.

---

src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogout_impl.cpp
src/digital/m2kdigital_impl.cpp

Destroy the buffer after canceling any operation.

Fix buffer canceling.

---

src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogout_impl.cpp
src/utils/devicegeneric.cpp
src/utils/devicegeneric.hpp

This provides a better accuracy and detection for certain features. Some setting should only be done for specific firmware version, but we can keep this as generic as possible if we are just checking the presence of those attributes.

General: Check if attributes exist instead of firmware version checking (where possible).

---

src/analog/m2kanalogin_impl.cpp
src/m2kcalibration_impl.cpp

Fix the computation of calibration offset.
Do not use calibscale for converting samples.

Calibration: Fix ADC calibration.

---

libm2k.iss.cmakein

The installer tried to replace the existing msvcp140.dll despite the "onlyifdoesntexist" flag. In this PR we introduced a function to check for its presence.
Also, the 32 bit installer should only install libiio and its dependencies if the "Install libiio" or "Overwrite libiio" is checked. This was missing from the 32bit install rules.

libm2k.iss: Fix libm2k installer

---

include/libm2k/m2khardwaretrigger.hpp
src/m2khardwaretrigger_impl.cpp
src/m2khardwaretrigger_impl.hpp
src/m2khardwaretrigger_v0.24_impl.cpp

The digital trigger source can be either "trigger-logic" or "trigger-in" (if we're talking about IIO attributes). In libm2k, we added SRC_TRIGGER_IN (trigger-logic), SRC_ANALOG_IN (trigger-in) and SRC_NONE.
The third should also point to "trigger-logic", because that is the default value for this attribute. However, we didn't check this when calling "getDigitalSource". This commit should verify whether there is a trigger condition attached to this source and return SRC_NONE or SRC_TRIGGER_IN
accordingly.

M2kHardwareTrigger: Fix digital source confusion when retrieving its value

---

include/libm2k/analog/m2kanalogin.hpp
include/libm2k/analog/m2kanalogout.hpp
include/libm2k/m2k.hpp
include/libm2k/m2kcalibration.hpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogin_impl.hpp
src/analog/m2kanalogout_impl.cpp
src/m2k_impl.cpp
src/m2k_impl.hpp
src/m2kcalibration_impl.cpp
src/m2kcalibration_impl.hpp

Expose to the user some methods which overwrite the ADC and DAC calibration gain and offset. Those will affect the read/written data. The values can be reset using the automatic calibration().

DAC and ADC calibration coefficients setters.

---

include/libm2k/analog/genericanalogout.hpp
include/libm2k/analog/m2kanalogout.hpp
src/analog/generic/genericanalogout_impl.cpp
src/analog/generic/genericanalogout_impl.hpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogout_impl.cpp
src/analog/m2kanalogout_impl.hpp

- Fix the cyclic attribute for Generic Analog Out.
- Add a channel name getter for M2k Analog Out.

M2K and Generic DAC fixes.

---

bindings/python/CMakeLists.txt

bindings/python: Fix CMake Policy warnings related to SWIG module name and generated target name.
Related to issue #139 .

bindings/python: Fix CMake Policy warnings related to SWIG.

---

include/libm2k/analog/m2kanalogin.hpp
include/libm2k/analog/m2kanalogout.hpp
include/libm2k/digital/m2kdigital.hpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogout_impl.cpp
src/digital/m2kdigital_impl.cpp
src/utils/buffer.cpp

The buffer canceling leaves the buffer in an invalid state. It should be
used only to disrupt a blocked operation.  It should not be used if the
buffer is not currently performing a blocking operation.
However, this operation should not include buffer destroying. The
destroy is done by managing the buffer state after refill/push
operations.

Revert cancel acquisition commit which added a buffer destruction

---

src/analog/m2kanalogout_impl.cpp

In this case, the push should work, so we need to check if both channels
have data assigned before using the dma_start_sync attributed. This
attribute will block the write until we have data on all the channels.

M2kAnalogOut: The synced push can also contain data for only one channel.

---

appveyor.yml
bindings/python/CMakeLists.txt

Use the OLD cmake_policy for CMP0078. This policy is related to the SWIG generated library name. For older versions, the name of the module and the target would be modify inside the
swig_add_library function.
The new version would keep the exact same name for the generated target.
A constant fix for both versions would mean a change of name for the python
module (which is not accepted right now).
Until we find a better solution we will use the OLD behaviour for all the
CMake versions (since this was proven to work until now) and we'll work
on finding a better solution until the moment of deprecation.

Fix issues related to Python bindings .

---

src/contextbuilder.cpp

In some rare cases, one or more attributes might be missing from the iio
context. This commit adds the validation for each attribute, in order to
avoid a null pointer exception.

ContextBuilder: Validate context info.

---

include/libm2k/analog/genericanalogin.hpp
include/libm2k/analog/m2kanalogin.hpp
include/libm2k/analog/m2kanalogout.hpp
src/analog/generic/genericanalogin_impl.cpp
src/analog/generic/genericanalogin_impl.hpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogin_impl.hpp
src/analog/m2kanalogout_impl.cpp
src/analog/m2kanalogout_impl.hpp
src/m2khardwaretrigger_impl.cpp

-These new features were necessary for integrating libm2k into Scopy.
-The trigger level fix refers to a computation error done when converting volts to raw samples.

Fix trigger level computation and add missing features.

---

src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogin_impl.hpp
src/analog/m2kanalogout_impl.cpp
src/analog/m2kanalogout_impl.hpp
src/contextbuilder.cpp
src/m2k_impl.cpp
src/m2k_impl.hpp

Unplugging the board from the PC might lead to undefined behaviour using the current libm2k.
These fixes will move some deinitialization steps outside the destructor and will handle the device destruction properly.
Also, the vertical offset should only be set to 0 if the firmware version is older and does not contain the "calibbias" attribute.

M2k destruction: Fix some issues related to context destruction and deinit. 

---

src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogin_impl.hpp
src/m2kcalibration_impl.cpp

M2kCalibration: Don't try to load the old vertical offset for firmware which does not contain the calibbias attribute.

---

examples/analog/CMakeLists.txt
examples/analog/stream_test_adc.cpp
examples/analog/stream_test_dac.cpp

It is provided as a command line interface, some of the arguments need to be passed by the
user.

examples: Add DAC and ADC streaming example. 

---

include/libm2k/m2kexceptions.hpp
src/utils/buffer.cpp
src/utils/buffer.hpp
src/utils/devicein.cpp
src/utils/deviceout.cpp

When a timeout occur in the refill/push process, a specific error is thrown for a more appropriate handling of the given situation.

Buffer: Handle timeout exception.

---

include/libm2k/analog/m2kanalogin.hpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogin_impl.hpp

The state of the channels should dictate whether a channel will acquire samples. Because m2k always needs both channels enabled in order to retrieve correct samples the following behaviour will be applied for getting samples:
- interleaved acquisition methods will always return the samples from both channels regardless of the original state of the channels
- acquisition methods that returns the samples as separate arrays will take in consideration the state of the channels

M2kAnalogIn: Return samples only from the enabled channels.

---

examples/connect.cpp
include/libm2k/enums.hpp
include/libm2k/m2kexceptions.hpp
src/analog/dmm_impl.cpp
src/analog/generic/genericanalogin_impl.cpp
src/analog/generic/genericanalogout_impl.cpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogout_impl.cpp
src/analog/m2kpowersupply_impl.cpp
src/context_impl.cpp
src/contextbuilder.cpp
src/digital/m2kdigital_impl.cpp
src/lidar_impl.cpp
src/m2k_impl.cpp
src/m2kcalibration_impl.cpp
src/m2kexception.cpp
src/m2khardwaretrigger_impl.cpp
src/m2khardwaretrigger_v0.24_impl.cpp
src/utils/buffer.cpp
src/utils/channel.cpp
src/utils/devicegeneric.cpp
src/utils/devicein.cpp
src/utils/deviceout.cpp
src/utils/utils.cpp

Create a general exception that contains a message, a type and an error code.
These modifications were added because of the necessity of handling different situation depending on the iio error code.
TODO:

M2kException:  Refactor exception throwing mechanism.

---

src/utils/buffer.cpp

These modifications prevent the creation of an empty buffer, in order to avoid the raise of an exception.
The changes present in #163 revealed a bug when empty buffers are pushed. This commit fixes this bug.

Buffer: Handle empty TX buffers.

---

bindings/python/examples/mixed_signal_view.py
include/libm2k/digital/m2kdigital.hpp
include/libm2k/enums.hpp
include/libm2k/m2k.hpp
src/digital/m2kdigital_impl.cpp
src/digital/m2kdigital_impl.hpp
src/m2k_impl.cpp
src/m2k_impl.hpp
src/m2khardwaretrigger_v0.24_impl.cpp

startMixedSignalAcquisition simplifies the process of acquiring mixed signals, that are synchronized one with the other. This process, for an end-user, will be reduced to:
- setting the same sampling frequency for both components
- calling startMixedSignalAcquisition method
- extracting the samples using getSamples() methods from both OSC and LA
This enhancement is described in #147.

Mixed signal acquisition.

---

bindings/python/CMakeLists.txt

python/CMakeLists: Install Python bindings on MacOS when running "make install".

---

src/m2k_impl.cpp

For the case where there is a trigger either on the analog interface or digital interface, we need to disable the triggering interface in order to block the acquisition. When both analog and digital interfaces are started we then release the corresponding trigger. Otherwise there will be a larger delay due to the analog acquisition being started much sooner than the digital acquisition.
Signed-off-by: DanielGuramulta <Daniel.Guramulta@analog.com>

M2kImpl: block the digital/analog interface until started

---

src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogout_impl.cpp
src/m2kcalibration_impl.cpp
src/m2kcalibration_impl.hpp

Previously stopAcquisition was only after calibrating ADC and DAC
alltogether. This causes the calibration to use continous buffer values
between calibration steps. ADC read does about 22 reads (one for offset
20 for fine tuning the offset and another one for gain), while DAC
calibration makes use of the ADC to calibrate offset and gain with one
read each. The buffers were continous to some measure due to the kernel
buffer configuration. By stopping the acquistion - we destroy the buffers
and force a reacquistion. This should give out better calibration values.

Calibration: Call stopAcquisition after every getSamplesRaw

---

include/libm2k/analog/m2kanalogin.hpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogin_impl.hpp

now only uses setSampleRate(value) and getSampleRate()
Signed-off-by: Cristina Suteu <cristina.suteu@analog.com>

M2kAnalogIn: remove channel index from sample rate methods

---

src/analog/m2kanalogin_impl.cpp

Thix fixes a bug that happend when `startAcquisition` is used, that caused invalid data to be captured.
﻿Signed-off-by: DanielGuramulta <Daniel.Guramulta@analog.com>

M2kAnalogIn: enable all channels before initializing the buffer

---

include/libm2k/m2kcalibration.hpp
src/m2k_impl.cpp
src/m2kcalibration_impl.cpp
src/m2kcalibration_impl.hpp

This is because for older firmware you cannot tell whether the voffset
has been calibrated or not. This causes an offset when using default values
even though isCalibrated returns true

M2KCalibration: use calibration done flags for firmware 0.25 and earlier

---

bindings/python/calibration/README.md
bindings/python/calibration/generate_temperature_calib_lut.py
include/libm2k/enums.hpp
include/libm2k/m2k.hpp
src/context_impl.hpp
src/m2k_impl.cpp
src/m2k_impl.hpp

An ini file with predefined calibration values can be generated or manually written. All its content will be written inside a context attribute at boot time if the file is added inside m2k driver. Then a fast calibration can be performed by using calibrateFromContext() method.
The purpose of this calibration type is to automate and to make the calibration
process more efficient.
This enhancement is described in #89.

Calibrate using predefined values

---

src/contextbuilder.cpp

ContextBuilder: Validate if the context has the 'usb,libusb' attribute.

---

include/libm2k/analog/m2kanalogin.hpp
include/libm2k/analog/m2kanalogout.hpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogin_impl.hpp
src/analog/m2kanalogout_impl.cpp
src/analog/m2kanalogout_impl.hpp
src/m2kcalibration_impl.cpp
src/m2kcalibration_impl.hpp
src/utils/devicegeneric.cpp
src/utils/devicegeneric.hpp
src/utils/deviceout.cpp

Fine tuning runs about 20 times. This creates the buffer, fills it and
destroys it right after. We reduce the amount of time spent here by
using the kernel buffers and the fact that the buffer is refilled instantly
after the buffer is created.
This reduces the calibration time with almost 1s.
Ran some tests to check calibration accuracy, results are the following:
> Test 1: Reset and get default values
2048 2048 1.0 1.0 2048 2048 0.718079 0.718079
CH0  0.028281165357529826
CH1  0.01082365587757312
>Test 2: Reading values after Scopy v1.2.0 did the calibration.
2011 2021 1.066284 1.075745 2072 2075 0.646606 0.639526
CH0  -0.005844470565028971
CH1  -0.0020493598085166514
>Test 1: Reset and get default values
2048 2048 1.0 1.0 2048 2048 0.718079 0.718079
CH0  0.02727925611781052
CH1 …

M2kCalibration: Reduce the time spent on the calibration process.

---

include/libm2k/analog/m2kpowersupply.hpp
src/analog/m2kpowersupply_impl.cpp
src/analog/m2kpowersupply_impl.hpp

This will specify whether the calibration coefficients should be used in the raw/volts conversion.

M2kPowerSupply: Add a boolean "calibrated" flag to the push and read methods.

---

include/libm2k/utils/utils.hpp
src/analog/m2kpowersupply_impl.cpp
src/m2k_impl.cpp
src/utils/utils.cpp

Use imbue to associate a locale to the stream and stream buffer.
std::stod behaviour changes based on the system locale, we made these
changes to avoid wrong parameter conversion.
Check if the generated calibration parameters file depends on the system locale (42.5 degrees or 42,5 degrees affect the way values are loaded into the library)

General: Replace "std:stod" with string streams

---

include/libm2k/analog/m2kanalogout.hpp
src/utils/buffer.cpp

Due to a hardware limitation, in cyclic mode the length of the buffers should be greater than 1024.
Add info in the documentation.
Add warning for the end-user.
Fixes #161

M2kAnalogOut: Add warning for small buffers.

---

azure-pipelines.yml

This can be found via:
https://dev.azure.com/AnalogDevices/_apis/projects?api-version=5.0
Since this yaml file was migrated from the OpenSource project, it needs to
explicitly define the GUID. Maybe a smarter mechanism could be implemented
later to pull it via the OpenSource project name.
Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>

ci,azure-pipelines: update AnalogDevices OpenSource GUID

---

libm2k.iss.cmakein

installing.
The libm2k-sharp.dll is added as a reference to a C# project, so the
compiler will manually copy it to the build directory.
But the libm2k-sharp-cxx-wrap.dll needs to be copied manually in the
build directory, and can't be added as a reference to a C# project.
This raises lots of issues. If we place it in the system folder, any DLL
that needs it, will find it in the Path.

libm2k.iss.cmakein: Copy the C++ -> C# wrapper DLL into System32 when

---

include/libm2k/analog/m2kanalogout.hpp
src/analog/m2kanalogout_impl.cpp
src/analog/m2kanalogout_impl.hpp
src/utils/buffer.cpp
src/utils/buffer.hpp
src/utils/devicegeneric.cpp
src/utils/devicegeneric.hpp

Check if the generation of the signal (only for non-cyclic buffer) is done.
Buffer: Add getNbSamples().
DeviceGeneric Add getNbSamples():
Fixes: #156.

M2kAnalogIn: Add isPushDone method.

---

src/utils/utils.cpp

LLVM/clang allows std::sort to compare the same element with itself.
The previous implementation returned both false and true when comparing
two identical elements (depending on position). This goes against the
"strict weak ordering" policy mandatory for std::sort.

utils.cpp: Fix undefined behaviour in std::sort on MacOS.

---

53-adi-m2k-usb.rules

The modern way to allow console users access to USB gadgets is the uaccess tag.
Signed-off-by: A. Maitland Bottoms <bottoms@debian.org>

udev add uaccess tag

---

src/contextbuilder.cpp

Improve version reporting for the case without a git hash,
such as a release version, or tarball package build.
Signed-off-by: A. Maitland Bottoms <bottoms@debian.org>

cleaner release version

---

src/analog/m2kanalogin_impl.cpp

GetVoltage() is not a buffered operation so it should not be affected
in any way by the number of kernel buffers.
Also, it should not affect the buffer and leave the device in a busy (maybe
even unusable) state.

M2kAnalogIn: Fix getVoltage() behaviour.

---

CI/appveyor/build_appveyor_msvc.sh
CI/appveyor/install_deps_msvc.sh
appveyor.yml

Lock the libiio version at hash 52e6dc3 for now.

appveyor: Build the latest libiio version.

---

bindings/libm2k.i

libm2k.i: Add definition for contexts info vector in the swig py bindings

---

bindings/libm2k.i

The problem appears when trying to iterate through a std::vector of
structs, exported using SWIG.

libm2k.i: Remove the 'struct' keyword as it does not behave well.

---

bindings/libm2k.i
include/libm2k/analog/m2kanalogin.hpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogin_impl.hpp

Due to some known limitation, the MATLAB wrappers need to request the
total number of samples, instead of requesting number of samples per channel.
We added 2 new API methods only for the MATLAB wrappers. This way, the
behaviour until now for all the other bindings available won't be affected.

Matlab bindings: Fix ADC acquisition.

---

tools/m2kcli/commands/context/context.cpp
tools/m2kcli/commands/context/context.h
tools/m2kcli/main.cpp

added context component which retrieves the following context attributes:
- firmware version
- iio version
- linux version
- hardware model
- product name 
- serial number
- device temperature
- vendor
- uri
- libusb version
Signed-off-by: cristina-suteu <cristina.suteu@analog.com>

tools/m2kcli: added context component

---

src/digital/m2kdigital_impl.cpp

added stopBufferOut() to reset()
This ensures the number of kernel buffers can be set when calling the reset method for the digital object. 
Signed-off-by: cristina-suteu <cristina.suteu@analog.com>

M2kDigital: fix reset

---

tools/m2kcli/examples/data_logger.sh

Added m2kcli data logger example to be used in the M2K Datalogger Tutorial
Signed-off-by: cristina-suteu <cristina.suteu@analog.com>

m2kcli/examples: added data_logger example

---

bindings/python/examples/analog.py
bindings/python/examples/analog_raw_bytes.py
bindings/python/examples/analogin_sync_2m2ks.py
bindings/python/examples/audio_flip.py
bindings/python/examples/digital.py
bindings/python/examples/digitalin_sync_2m2ks.py
bindings/python/examples/external_clocksource.py
bindings/python/examples/mixed_signal_view.py
bindings/python/examples/powersupply.py
bindings/python/examples/voltmeter.py
examples/analog/analog_in_out.cpp
examples/analog/stream_test_adc.cpp
examples/analog/stream_test_dac.cpp
examples/analog/streaming_one_channel.cpp
examples/analog/streaming_synchronized.cpp
examples/analog/sync_stream_diff_frequencies.cpp

Some examples don't handle all the possible attributes (oversampling_ratio).
If the analogIn or analogOut object are not reset before using, the
result might be wrong.

Examples: Add reset() to examples, before calibrating the ADC and DAC.

---

doc/mainpage.dox

mainpage.dox: Link to the correct python folder for the python docs.

---

CI/appveyor/install_deps_msvc.sh

appveyor: Update libiio to version v0.23 + 2 fixes from the master branch.

---

src/context_impl.cpp
src/generic_impl.cpp

It makes more sense for the devices to be in ascending order, so the indexes correspond to their position:
getAnalogIn/Out(index)

GenericImpl: Sort ascending input and output devices.

---

include/libm2k/contextbuilder.hpp
src/context_impl.cpp
src/context_impl.hpp
src/contextbuilder.cpp

ContextBuilder: Make sure iio_context_destroy is called by the object  that  has ownership over the created iio_context.

---

tools/m2kcli/commands/communication/uart_terminal.cpp
tools/m2kcli/utils/validator.cpp

Solve the following warnings.
tools/m2kcli/commands/communication/uart_terminal.cpp:263:39: warning: catching polymorphic type ‘class std::runtime_error’ by value [-Wcatch-value=]
263 |                         } catch (std::runtime_error) {
|                                       ^~~~~~~~~~~~~
tools/m2kcli/utils/validator.cpp:111:33: warning: catching polymorphic type ‘class std::exception’ by value [-Wcatch-value=]
111 |         } catch (std::exception e) {
tools/m2kcli/utils/validator.cpp:120:33: warning: catching polymorphic type ‘class std::exception’ by value [-Wcatch-value=]
120 |         } catch (std::exception e) {
Signed-off-by: Cosmin Tanislav <demonsingur@gmail.com>

m2kcli: fix catching polymorphic type by value

---

src/m2kcalibration_impl.cpp
src/utils/devicegeneric.cpp
src/utils/deviceout.cpp
src/utils/deviceout.hpp
tests/analog_functions.py
tests/digital_functions.py
tests/m2k_analog_test.py
tests/m2k_digital_test.py
tests/main.py

Calling set_kernel_buffers_count() right after destroying a buffer might
return EBUSY because the file descriptor is still in use.

devicegeneric.cpp: Implement a busy retry when trying to write the kernel buffers count.

---

tools/m2kcli/examples/m2k_tty.sh

The script connects the UART-Terminal to a PTY in order to communicate with a device using a Serial Terminal Emulator.
It uses the socat command to create two connected PTYs (pseudoterminal interfaces) and using the m2kcli uart-terminal command makes the connection between a PTY and our UART-Terminal.
The user can connect to the other PTY using a serial port terminal emulator (like GTKTerm, Picocom, Minicom, Tera Term).
More details [here](https://wiki.analog.com/university/tools/m2k/libm2k/m2kcli#usb_to_serial_uart_adapter_script).
Signed-off-by: Cristian Bindea <cristian.bindea@analog.com>

m2kcli/examples: added m2k_tty.sh script

---

bindings/python/setup.py.cmakein

bindings/python/setup.py.cmakein: Drop python_requires attribute which is not supported in some setups.

---

bindings/matlab/bsp.tmpl
bindings/matlab/build_installer.m

generated new uuid for matlab bindings project in build template 
update build installer to match the correct version of matlab (Matlab 2022b)

update build tamplate and build installer for matlab 2022b

---

tests/m2k_analog_test.py

Added a skip for test phase difference in samples as suggested. The test has been consistently failing.

tests: analogtest: add skip for test phase diff in samples

---

tools/m2kcli/utils/validator.h

- explicitly included <cstdint> header for GCC 13 compilation

m2kcli/utils/validator.h: Compatibility with gcc 13

---

src/utils/devicegeneric.cpp

Failure means that the buffer was not yet destroyed, so the next call will probably fail as well if we don't delay the process.

DeviceGeneric.cpp: If the previous call failed, allow more time to settle.

---

tests/analog_functions.py
tests/digital_functions.py
tests/m2k_analog_test.py
tests/m2k_digital_test.py
tests/main.py

* Analog test that verifies that no glitch is present with changes made in firmware v0.32
* Investigation test for patter generator known bug that should be addressed in future firmware version..

tests/validations fw 0.32

---

src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogin_impl.hpp

- Sync class parameters: m_adc_calib_offset, m_adc_calib_gain with device attributes. These are used to calibrate the raw data to volts.
- In firmware version 0.32, the device attribute won't be used by the hardware, samples will be recieved uncalibrated. The calibration will be done in software.
- In new libm2k, use the calibration attr is used to disable setting the computed calibration values in HW.
- Note: - set calibration = 'true' (string vale): stops the HW calibration - set calibration = 'false' (string value): enables the HW calibration

fw0.32/adc_calib: sync calibration state and use new attribute to decouple HW calibration

---

include/libm2k/contextbuilder.hpp
src/contextbuilder.cpp

- added reference count to ContextBuilder to keep track of how many external references to the M2k context are present. When the last reference is removed, the M2k context can be closed.
- contexts should be closed in the reverse order they were opened: contextClose() -> iio_context_destroy() to avoid pointer errors.
- based on context ownership, the user of the API is responsible of deinitalizing resources.

ContextBuilder: solve context close bug using reference count

---

doc/Doxyfile_API.in
include/libm2k/analog/dmm.hpp
include/libm2k/analog/enums.hpp
include/libm2k/analog/m2kanalogin.hpp
include/libm2k/analog/m2kanalogout.hpp
include/libm2k/analog/m2kpowersupply.hpp
include/libm2k/context.hpp
include/libm2k/digital/m2kdigital.hpp
include/libm2k/enums.hpp
include/libm2k/m2k.hpp
include/libm2k/m2khardwaretrigger.hpp

In order to have reproducible builds with documentation, these Doxygen settings and markup changes are needed. (Previously the build path got put into HTML files.)

doc omit build path

---

tools/communication/src/i2c.cpp

- Modified SDA to transition 1/4 Tbit earlier, ensuring data stability when SCL is high.
- Adjusted the early transition in the start condition to leverage the open drain configuration of I2C, which ensures both lines are high initially.
Resolves issue #365

tools/i2c: Ensure SDA stability during SCL transitions

---

tests/digital_functions.py
tests/m2k_digital_test.py
tests/main.py

The test was updated to identify glitches in the PG signal across all DIO channels. Test is done for each DIO channel separately as well as for all DIO channels at once.

tests/digital: coverage of features introduced in fw0.33

---

tests/analog_functions.py
tests/bug_checks_functions.py
tests/digital_functions.py
tests/helpers.py
tests/m2k_analog_test.py
tests/m2k_digital_test.py
tests/main.py
tests/reset_def_values.py
tests/shapefile.py

- Validate last sample hold functionality.
- Validate DAC triggering.
- Validate that a reset to the M2kAnalogOut  brings the channel to 0V using the RAW attribute as source.
The tests cover the new features introduced, and detect bugs and issues encountered during development

tests/analog: validate M2kAnalogOut features introduced in fw0.33

---

tests/README.md
tests/dual_board/dac_triggered_test.py

- Add a subdirectory for tests that run as standalone scripts which require x2 M2K's to cover synchronization

tests: dual board tests

---

CI/windows/make_windows.ps1

- The missing file was necessary in the generation step of the Matlab bindings.

ci/windows: add missing artifact export

---

CI/ubuntu/doxygen.sh
CI/ubuntu/make_linux

- The build directory for libiio was left dangling, causing documentation generation to fail as it was recognized as a submodule.

ci/docs: delete dangling libiio build directory
