include/libm2k/analog/m2kanalogout.hpp
src/analog/private/m2kanalogout_impl.cpp

Fix DAC powerdown

---

include/libm2k/context.hpp
include/libm2k/contextbuilder.hpp
src/context.cpp
src/contextbuilder.cpp
src/private/context_impl.cpp

Create M2k object based on iio_context

---

.gitignore

Add ignore rules for pycache directories, python eggs and hidden dirctories.

Add ignore rules for pycache directories, python eggs and hidden directories.

---

tools/python/sine_gen.py

Tools: added Python sinewave generator tool

---

include/libm2k/analog/enums.hpp
include/libm2k/digital/enums.hpp
include/libm2k/enums.hpp

This makes the documentation for enums and structures more readable.

Documentation: Some minor changes to the Doxygen documentation.

---

tools/communication/src/utils/util.cpp
tools/communication/src/utils/util.h

Those functions are used for bitbanging.

Communication(4): Add util functions.

---

bindings/csharp/examples/spi.cs
bindings/libm2k.i
bindings/python/examples/spi.py
include/libm2k/tools/spi.hpp
include/libm2k/tools/spi_extra.hpp
tools/communication/examples/CMakeLists.txt
tools/communication/examples/spi/CMakeLists.txt
tools/communication/examples/spi/main.cpp
tools/communication/src/spi.cpp
tools/m2kcli/commands/communication/spi.cpp
tools/m2kcli/commands/communication/spi.h
tools/m2kcli/examples/spi.sh
tools/m2kcli/main.cpp

Add SPI tools: bitbanging and CLI.

Communication(2): SPI

---

bindings/csharp/examples/i2c.cs
bindings/libm2k.i
bindings/python/examples/i2c.py
include/libm2k/tools/i2c.hpp
include/libm2k/tools/i2c_extra.hpp
tools/communication/examples/CMakeLists.txt
tools/communication/examples/i2c/CMakeLists.txt
tools/communication/examples/i2c/main.cpp
tools/communication/src/i2c.cpp
tools/m2kcli/commands/communication/i2c.cpp
tools/m2kcli/commands/communication/i2c.h
tools/m2kcli/examples/i2c.sh
tools/m2kcli/main.cpp

Add I2C tools: bitbanging and CLI.

Communication(3): I2C

---

.travis.yml
CI/travis/doxygen.sh

Remove hardcoded username, repo name, and include secure github token generated from ADI github account
Signed-off-by: Daniel Guramulta <daniel.guramulta@analog.com>

ci: travis: add secure github token

---

bindings/csharp/examples/uart.cs
bindings/libm2k.i
bindings/python/examples/uart.py
include/libm2k/tools/uart.hpp
include/libm2k/tools/uart_extra.hpp
tools/communication/examples/CMakeLists.txt
tools/communication/examples/uart/CMakeLists.txt
tools/communication/examples/uart/main.cpp
tools/communication/src/uart.cpp
tools/m2kcli/commands/command.cpp
tools/m2kcli/commands/command_out.cpp
tools/m2kcli/commands/command_out.h
tools/m2kcli/commands/communication/uart.cpp
tools/m2kcli/commands/communication/uart.h
tools/m2kcli/examples/uart.sh
tools/m2kcli/main.cpp

Add UART tools: bitbanging and CLI.

Communication(5): UART

---

tools/m2kcli/commands/communication/uart_terminal.cpp
tools/m2kcli/commands/communication/uart_terminal.h
tools/m2kcli/examples/uart-terminal.sh
tools/m2kcli/main.cpp
tools/m2kcli/utils/conio.cpp
tools/m2kcli/utils/conio.h
tools/m2kcli/utils/linux_key_encoder.cpp
tools/m2kcli/utils/linux_key_encoder.h
tools/m2kcli/utils/safe_queue.h

Communication(6): UART Terminal

---

tests/README.md
tests/analog_functions.py
tests/digital_functions.py
tests/m2k_analog_test.py
tests/m2k_digital_test.py
tests/m2k_powersupply_test.py
tests/m2k_trigger_test.py
tests/main.py
tests/open_context_and_files.py
tests/ps_functions.py
tests/reset_def_values.py
tests/shapefile.py
tests/trig_functions.py

Test classes:
AnalogTests
PowerSupply
TriggerTest
DigitalTests(under development)

Add tests for libm2k. 

---

appveyor.yml
libm2k.iss.cmakein

appveyor.yml: Add missing Visual Studio dll.

---

libm2k.iss.cmakein

libm2k.iss: Check if Visual Studio dll already exists in the system.

---

tools/m2kcli/main.cpp

m2kcli --scan : Scan all available USB connection and retrieve the URIs.
m2kckli --identify <uri>: Identify the m2k based on an URI, by the blinking of its led.

M2kcli: Add scan and identify options.

---

bindings/csharp/examples/digital_stream_example.cs
bindings/libm2k.i

bindings/csharp: Modify the digital streaming example in order to increase the possible streaming speed.
The speed depends on the number of samples requested in one buffer

examples: Digital stream example C#

---

include/libm2k/analog/m2kanalogout.hpp
include/libm2k/digital/m2kdigital.hpp
src/analog/m2kanalogout.cpp
src/analog/private/m2kanalogout_impl.cpp
src/digital/m2kdigital.cpp
src/digital/private/m2kdigital_impl.cpp

Digital and AnalogOut: Allow the user to retrieve the number of channels for these devices.

---

CMakeLists.txt

CMakeLists.txt: Change udev rules var name to libm2k_udev_rules.

---

bindings/csharp/examples/digital_stream_example.cs
bindings/python/examples/analog_raw_bytes.py
examples/digital/stream_test.cpp
include/libm2k/analog/m2kanalogin.hpp
include/libm2k/digital/m2kdigital.hpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogin_impl.hpp
src/digital/m2kdigital_impl.cpp
src/digital/m2kdigital_impl.hpp
src/m2kcalibration_impl.cpp
src/utils/buffer.cpp
src/utils/devicein.cpp
src/utils/devicein.hpp
tests/analog_functions.py
tests/trig_functions.py
tools/communication/src/i2c.cpp
tools/communication/src/spi.cpp
tools/communication/src/uart.cpp
tools/m2kcli/commands/communication/uart_terminal.cpp

Create the read buffer for M2kAnalogIn and M2kDigital.

M2k_Input_Devices: Initialize read buffer.

---

include/libm2k/contextbuilder.hpp
include/libm2k/enums.hpp
src/contextbuilder.cpp

Get additional information about the available contexts without opening any of them.

ContextBuilder: Get addition information about contexts.

---

src/analog/generic/genericanalogin_impl.cpp
src/analog/generic/genericanalogout_impl.cpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogout_impl.cpp
src/utils/channel.cpp
src/utils/channel.hpp
src/utils/devicegeneric.cpp
src/utils/devicegeneric.hpp
src/utils/utils.cpp

Create a generic method for retrieving the possible values for a given attribute.

Get attributes available values

---

.travis.yml
CI/travis/doxygen.sh
doc/sphinx/source/conf.py.in

-Update to bionic, to have Sphinx building fine with a newer version.
-Drop some broken Sphinx extension.
-Make sure Sphinx doc is building and gets deployed on the gh-pages.

.travis.yml: Fix the Travis CI Doxygen build.

---

examples/analog/stream_test_adc.cpp

Fix building warnings of the ADC streaming example. Some of these warnings cause the building process of Travis CI to fail.

Examples: Fix ADC streaming example warnings.

---

examples/connect.cpp
include/libm2k/m2kexceptions.hpp
src/analog/dmm_impl.cpp
src/analog/generic/genericanalogin_impl.cpp
src/analog/generic/genericanalogout_impl.cpp
src/analog/m2kanalogin_impl.cpp
src/analog/m2kanalogout_impl.cpp
src/analog/m2kpowersupply_impl.cpp
src/context_impl.cpp
src/contextbuilder.cpp
src/digital/m2kdigital_impl.cpp
src/lidar_impl.cpp
src/m2k_impl.cpp
src/m2kcalibration_impl.cpp
src/m2kexception.cpp
src/m2khardwaretrigger_impl.cpp
src/m2khardwaretrigger_v0.24_impl.cpp
src/utils/buffer.cpp
src/utils/channel.cpp
src/utils/devicegeneric.cpp
src/utils/devicein.cpp
src/utils/deviceout.cpp
src/utils/utils.cpp

Every m2k exception will contain the file and the line where the error occurred. These will be used for debugging purposes.

M2kException: Add extra information.

---

include/libm2k/context.hpp
include/libm2k/enums.hpp
src/context_impl.cpp
src/context_impl.hpp

Functionalities:
- retrieve the iio context
- get iio backend version

Context: Add extra functionalities.

---

cmake/readme.md

Specify more info on what linking against libm2k::libm2k(the target) means

cmake: update readme.md

---

src/digital/m2kdigital_impl.cpp

First try to catch m2k_exception, otherwise the iio code will be lost.
Fixes #204.

M2kDigital: Add missing m2k_exception.

---

CMakeLists.txt
bindings/python/CMakeLists.txt

CMakeLists.txt: Add support for versions less than 3.8.2.

---

CMakeLists.txt
include/libm2k/contextbuilder.hpp
src/contextbuilder.cpp

Add method to enable/disable the logging system.
The logging will be enabled/disabled immediately after the function is called.
Default behavior: logging system disabled.

ContextBuilder: Disable logging.

---

CI/appveyor/build_appveyor_msvc.sh
CI/appveyor/install_glog.bat
CMakeLists.txt
appveyor.yml
libm2k.iss.cmakein
src/CMakeLists.txt

Fix the issue for detecting glog when it is installed using apt-get.

CMakeLists: Fix glog detection issue.

---

bindings/python/examples/analogin_sync_2m2ks.py
bindings/python/examples/digitalin_sync_2m2ks.py

added python example for analog in interface
added python example for digital in interface
Signed-off-by: Cristina Suteu <cristina.suteu@analog.com>

Sync M2Ks Python Examples

---

azure-pipelines.yml

try to upload the tar packages as artifact in Azure pipelines

---

include/libm2k/m2kexceptions.hpp

cmake: fix exception definition for android

---

CI/appveyor/build_appveyor_msvc.sh
CI/appveyor/install_glog.bat
CI/travis/before_install_darwin
CI/travis/before_install_linux
CMakeLists.txt
appveyor.yml
libm2k.iss.cmakein
src/CMakeLists.txt

Fix glog detection and install.

---

bindings/libm2k.i

changed data type template VectorVectorS from vector< vector<int> > to vector< vector<short> >
added   VectorVectorI vector< vector<int> > data type template

Python: fix pushRaw() on both channles

---

tools/m2kcli/main.cpp

- Fix pure virtual method call.
- Change examples to executable files.
Fixes #230.

Fix m2kcli

---

include/libm2k/analog/m2kanalogin.hpp

doc: Fix description of getSamplesInterleaved and getSamplesRawInterleaved.

---

bindings/python/examples/external_clocksource.py
bindings/python/examples/external_clocksource_example.py
include/libm2k/digital/m2kdigital.hpp
src/digital/m2kdigital_impl.cpp
src/digital/m2kdigital_impl.hpp

added setter and getter for clock source attribute
added Python external clock source example

Logic Analyser External Clocksource

---

bindings/python/examples/audio_flip.py

Added Python example script used in the Intro to Libm2k tutorial video. 
Signed-off-by: Cristina Suteu <cristina.suteu@analog.com>

Python: added audio flip example

---

bindings/csharp/examples/spi.cs
bindings/python/examples/spi.py
include/libm2k/tools/spi_extra.hpp
tools/communication/examples/spi/main.cpp
tools/communication/src/spi.cpp
tools/m2kcli/commands/communication/spi.cpp
tools/m2kcli/examples/spi.sh

- Possible values for CS: ACTIVE_LOW, ACTIVE_HIGH.
- Update examples.
- Update m2kcli.
Mentioned in #250.

SPI: Add CS polarity.

---

CI/travis/doxygen.sh
CI/travis/make_linux
README.md
azure-pipelines.yml
bindings/csharp/README.md
bindings/labview/README.md
bindings/python/README.md
doc/mainpage.dox
include/libm2k/analog/m2kanalogin.hpp

- Added logos to readme pages.
- Added a build for doxygen on azure pipelines.
- Added logos to doxygen documentation

Documentation updates: Add logos to readme, add doxygen build on azure pipelines.

---

CI/travis/doxygen.sh
azure-pipelines.yml
doc/mainpage.dox

azure-pipelines.yml: Fix gh-pages deploy folder and sphinx doc path.

---

src/utils/buffer.cpp

buffer: performance improvement reserve data before pushing

---

include/libm2k/analog/enums.hpp
src/analog/dmm_impl.cpp

DMM: Modify struct to include unit name and symbol as defined by the International System of Units.

---

tools/communication/src/i2c.cpp
tools/communication/src/spi.cpp

Remove thread sleep and use atomic bool in order to synchronize both threads.
Initialize buffer before notifying the write thread.

spi & i2c: Synchronize read and write threads.

---

bindings/python/examples/expose_spi.py
include/libm2k/tools/spi_extra.hpp
tools/communication/src/spi.cpp

This new API provides the functionality of modifying the data inside the digital buffer before the transmission starts.

Expose spi create buffer

---

.github/workflows/build_wheels.yml
azure-pipelines.yml

testpypi: Small fixes for the "twine upload" step: no functional changes.

---

CI/travis/before_install_linux
azure-pipelines.yml

azure-pipelines.yml: Fix Linux build issues with libiio artifact path.

---

tests/README.md
tests/analog_functions.py
tests/bug_checks_functions.py
tests/create_files.py
tests/digital_functions.py
tests/logger.py
tests/m2k_analog_test.py
tests/m2k_bug_checks.py
tests/m2k_digital_test.py
tests/m2k_powersupply_test.py
tests/m2k_trigger_test.py
tests/main.py
tests/open_context.py
tests/ps_functions.py
tests/repeat_test.py
tests/requirements.txt
tests/reset_def_values.py
tests/shapefile.py
tests/trig_functions.py

updated tests structure
added option to suppress output files
added tests for the digital interface
added requirements.txt 
other small fixes

Tests Rework

---

tests/requirements.txt

tests: updated requirements.txt

---

src/m2k_impl.cpp
src/m2k_impl.hpp
src/utils/utils.cpp

m2k_impl.cpp:Check if the board is M2K-FMC and skip the fw_version check

---

tests/requirements.txt

Incomplete string comparison in the numpy.core component in NumPy1.9.x,
which allows attackers to fail the APIs via constructing specific string
objects.

tests: Update requirements versions after Dependabot alert for numpy.

---

bindings/matlab/build_library_linux64.m
bindings/matlab/build_library_win64.m
bindings/matlab/builder.m
bindings/matlab/definelibm2k.m
bindings/matlab/definelibm2k_linux64.m
bindings/matlab/definelibm2k_win64.m
bindings/matlab/test/libm2kTests.m

Signed-off-by:Ionut Muthi <Ionut.Muthi@analog.com>

generated new definelibm2k for win64 and linux64

---

bindings/matlab/deps.bat

updated the script to install the needed dependencies on windows
Signed-off-by:Ionut Muthi <Ionut.Muthi@analog.com>

updated deps script to run on windows

---

CI/ubuntu/doxygen.sh
README.md
bindings/python/README.md
doc/mainpage.dox
doc/sphinx/source/examples.rst

Change all the links to point to the new default branch and remove unused appveyor status badge.

README:Update README files and prepare the repo for the new default branch

---

bindings/python/examples/dc_sweep.py

- Added Python example covering both signal generation and data acquisition for DC sweep.
- Should be a good reference for EZ questions, [see here](https://ez.analog.com/adieducation/university-program/f/q-a/592786/adalm2000-dc-sweep/561129).

examples: DC Sweep 
